[platformio]
default_envs = blackpill_f411

[env:blackpill_f411]
platform       = ststm32
board          = blackpill_f411
framework      = arduino
build_flags    =
  -DMCU_STM32F411xE
  -DSTM32F4xx
  -DARDUINO_ARCH_STM32
upload_protocol = stlink
monitor_speed  = 115200
lib_ldf_mode   = deep
